import 'dart:typed_data';
import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:flutter_email_sender/flutter_email_sender.dart';
import 'package:intl/intl.dart';
import 'package:legalease/features/document_scan/domain/models/analysis_result.dart';

class ExportService {
  Future<Uint8List> generatePdf(AnalysisResult result) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _buildPdfHeader(result),
        footer: (context) => _buildPdfFooter(context),
        build: (context) => [
          _buildSummarySection(result),
          pw.SizedBox(height: 20),
          _buildRedFlagsSection(result),
          pw.SizedBox(height: 20),
          _buildTranslationSection(result),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildPdfHeader(AnalysisResult result) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 16),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'LegalEase Analysis Report',
                style: pw.TextStyle(
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blue800,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                result.metadata.fileName ?? 'Document',
                style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
              ),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(
                DateFormat('MMMM d, yyyy').format(result.analyzedAt),
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
              ),
              pw.Text(
                '${result.metadata.wordCount} words',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
              ),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _buildPdfFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 16),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by LegalEase',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildSummarySection(AnalysisResult result) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Document Summary',
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 12),
        pw.Container(
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius: pw.BorderRadius.circular(8),
          ),
          child: pw.Text(
            result.summary.isNotEmpty
                ? result.summary
                : 'No summary available.',
            style: const pw.TextStyle(fontSize: 11),
          ),
        ),
        pw.SizedBox(height: 16),
        pw.Row(
          children: [
            _buildInfoChip('Type', result.metadata.typeName),
            pw.SizedBox(width: 8),
            _buildInfoChip('Red Flags', '${result.redFlags.length}'),
            pw.SizedBox(width: 8),
            _buildInfoChip(
              'Confidence',
              '${(result.metadata.confidence * 100).toInt()}%',
            ),
          ],
        ),
      ],
    );
  }

  pw.Widget _buildInfoChip(String label, String value) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue50,
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Row(
        mainAxisSize: pw.MainAxisSize.min,
        children: [
          pw.Text(
            '$label: ',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
          pw.Text(
            value,
            style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildRedFlagsSection(AnalysisResult result) {
    if (result.redFlags.isEmpty) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Red Flags Analysis',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 12),
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.green50,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Row(
              children: [
                pw.Icon(pw.IconData(0xe5ca), size: 20, color: PdfColors.green),
                pw.SizedBox(width: 8),
                pw.Text(
                  'No red flags detected in this document.',
                  style: const pw.TextStyle(fontSize: 11),
                ),
              ],
            ),
          ),
        ],
      );
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Red Flags Analysis',
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 12),
        pw.Row(
          children: [
            _buildSeverityCount('Critical', result.criticalCount, PdfColors.red),
            pw.SizedBox(width: 16),
            _buildSeverityCount('Warning', result.warningCount, PdfColors.orange),
            pw.SizedBox(width: 16),
            _buildSeverityCount('Info', result.infoCount, PdfColors.blue),
          ],
        ),
        pw.SizedBox(height: 16),
        ...result.redFlags.map((flag) => _buildRedFlagItem(flag)),
      ],
    );
  }

  pw.Widget _buildSeverityCount(String label, int count, PdfColor color) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: pw.BoxDecoration(
        color: color.shade(50),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Row(
        mainAxisSize: pw.MainAxisSize.min,
        children: [
          pw.Text(
            '$count',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: color),
          ),
          pw.SizedBox(width: 4),
          pw.Text(label, style: pw.TextStyle(fontSize: 10, color: color)),
        ],
      ),
    );
  }

  pw.Widget _buildRedFlagItem(RedFlagItem flag) {
    PdfColor severityColor;
    switch (flag.severity) {
      case RedFlagSeverity.critical:
        severityColor = PdfColors.red;
        break;
      case RedFlagSeverity.warning:
        severityColor = PdfColors.orange;
        break;
      case RedFlagSeverity.info:
        severityColor = PdfColors.blue;
        break;
    }

    final quotedText = flag.originalClause.length > 200
        ? '"${flag.originalClause.substring(0, 200)}..."'
        : '"${flag.originalClause}"';

    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 12),
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: severityColor.shade(200)),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                decoration: pw.BoxDecoration(
                  color: severityColor.shade(100),
                  borderRadius: pw.BorderRadius.circular(4),
                ),
                child: pw.Text(
                  flag.severityLabel.toUpperCase(),
                  style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: severityColor),
                ),
              ),
              pw.Text(
                '${(flag.confidenceScore * 100).toInt()}% confidence',
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
              ),
            ],
          ),
          pw.SizedBox(height: 8),
          pw.Container(
            padding: const pw.EdgeInsets.all(8),
            decoration: const pw.BoxDecoration(color: PdfColors.grey100),
            child: pw.Text(
              quotedText,
              style: pw.TextStyle(fontSize: 10, fontStyle: pw.FontStyle.italic),
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            flag.explanation,
            style: const pw.TextStyle(fontSize: 10),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildTranslationSection(AnalysisResult result) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Plain English Translation',
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 12),
        pw.Container(
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            color: PdfColors.grey50,
            borderRadius: pw.BorderRadius.circular(8),
            border: pw.Border.all(color: PdfColors.grey200),
          ),
          child: pw.Text(
            result.plainEnglishTranslation.isNotEmpty
                ? result.plainEnglishTranslation
                : 'Translation not available.',
            style: const pw.TextStyle(fontSize: 11),
          ),
        ),
      ],
    );
  }

  Future<String> saveToFile(Uint8List data, String filename) async {
    final directory = await getApplicationDocumentsDirectory();
    final file = File('${directory.path}/$filename');
    await file.writeAsBytes(data);
    return file.path;
  }

  Future<void> shareDocument(Uint8List data, String filename) async {
    await Printing.sharePdf(bytes: data, filename: filename);
  }

  Future<void> printDocument(Uint8List data) async {
    await Printing.layoutPdf(onLayout: (_) => data);
  }

  Future<void> exportToCounsel({
    required AnalysisResult result,
    required String attorneyEmail,
    String? attorneyName,
    String? customMessage,
  }) async {
    final pdfData = await generatePdf(result);
    final filename = 'LegalEase_Analysis_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final filePath = await saveToFile(pdfData, filename);

    final email = Email(
      body: _buildEmailBody(result, customMessage),
      subject: 'Document Analysis: ${result.metadata.fileName ?? 'Legal Document'}',
      recipients: [attorneyEmail],
      attachmentPaths: [filePath],
      isHTML: false,
    );

    await FlutterEmailSender.send(email);
  }

  String _buildEmailBody(AnalysisResult result, String? customMessage) {
    final buffer = StringBuffer();

    if (customMessage != null && customMessage.isNotEmpty) {
      buffer.writeln(customMessage);
      buffer.writeln();
      buffer.writeln('---');
      buffer.writeln();
    }

    buffer.writeln('Document Analysis Summary');
    buffer.writeln('Generated by LegalEase on ${DateFormat('MMMM d, yyyy').format(result.analyzedAt)}');
    buffer.writeln();
    buffer.writeln('Document: ${result.metadata.fileName ?? 'Unknown'}');
    buffer.writeln('Type: ${result.metadata.typeName}');
    buffer.writeln('Word Count: ${result.metadata.wordCount}');
    buffer.writeln();
    buffer.writeln('Analysis Results:');
    buffer.writeln('- Total Red Flags: ${result.redFlags.length}');
    buffer.writeln('- Critical: ${result.criticalCount}');
    buffer.writeln('- Warnings: ${result.warningCount}');
    buffer.writeln('- Info: ${result.infoCount}');
    buffer.writeln();
    buffer.writeln('Please find the detailed analysis report attached.');

    return buffer.toString();
  }

  String generateChatExportPdf(List<Map<String, dynamic>> messages, String documentTitle) {
    final buffer = StringBuffer();
    buffer.writeln('Chat Export: $documentTitle');
    buffer.writeln('Generated: ${DateFormat('MMMM d, yyyy HH:mm').format(DateTime.now())}');
    buffer.writeln();
    buffer.writeln('=' * 50);
    buffer.writeln();

    for (final message in messages) {
      final role = message['role'] ?? 'user';
      final content = message['content'] ?? '';
      final timestamp = message['timestamp'] != null
          ? DateFormat('HH:mm').format(DateTime.parse(message['timestamp']))
          : '';

      buffer.writeln('[${role.toUpperCase()}] ${timestamp.isNotEmpty ? 'at $timestamp' : ''}');
      buffer.writeln(content);
      buffer.writeln();
      buffer.writeln('-' * 30);
      buffer.writeln();
    }

    return buffer.toString();
  }
}
